#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# --- CONFIGURATION ---
VPS_USER="root"
VPS_HOST="todue.ethandean.dev"
VPS_DEST_DIR="~/deployments/td"        # Directory on VPS where the jar lives
JAR_NAME="todue-0.1.0.jar"             # Name of the jar on the server (referenced by pm2)
# ---------------------

echo "=========================================="
echo "🚀 Starting Deployment Process"
echo "=========================================="

# 1. Build Frontend
echo "📦 Building Frontend (Web)..."
cd web
npm run build
cd ..

# 2. Copy Frontend to Backend
echo "dV Checking Backend Static Resources..."
STATIC_DIR="backend/todue/src/main/resources/static"

# Ensure directory exists
mkdir -p "$STATIC_DIR"

# Clean old static files to ensure no stale assets
echo "🧹 Cleaning old static files..."
rm -rf "$STATIC_DIR"/*

# Copy new build artifacts (Vite builds to dist/)
echo "mb Copying new frontend build to Spring Boot..."
cp -r web/dist/* "$STATIC_DIR/"

# 3. Build Backend
echo "☕ Building Backend (Spring Boot)..."
cd backend/todue
# Using -DskipTests to speed up deploy, remove if you want to run tests every time
./mvnw clean package -DskipTests

# Locate the built JAR (ignoring the .original file generated by Maven)
BUILT_JAR=$(ls target/*.jar | grep -v '\.original$' | head -n 1)
echo "✅ Backend built: $BUILT_JAR"

# Go back to root
cd ../..

# 4. Transfer to VPS
echo "bw Uploading JAR to VPS ($VPS_HOST)..."
scp "backend/todue/$BUILT_JAR" "$VPS_USER@$VPS_HOST:$VPS_DEST_DIR/$JAR_NAME"

# 5. Restart Service
echo "qc Restarting Application on VPS..."
ssh "$VPS_USER@$VPS_HOST" "pm2 restart td_prod"

echo "=========================================="
echo "✨ Deployment Complete!"
echo "=========================================="
