#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# --- CONFIGURATION ---
VPS_USER="ubuntu"
VPS_HOST="129.213.58.208"
VPS_DEST_DIR="~/deployments/td"        # Directory on VPS where the jar lives
JAR_NAME="todue-0.1.0.jar"             # Name of the jar on the server (referenced by pm2)
SERVICE_NAME="todue"                   # Systemd service name
# ---------------------

echo "=========================================="
echo "🚀 Starting Deployment Process"
echo "=========================================="

# 1. Build Frontend
echo "📦 Building Frontend (Web)..."
cd web
npm run build
cd ..

# 2. Copy Frontend to Backend
echo "📂 Checking Backend Static Resources..."
STATIC_DIR="backend/todue/src/main/resources/static"

# Ensure directory exists
mkdir -p "$STATIC_DIR"

# Clean old static files to ensure no stale assets
echo "🧹 Cleaning old static files..."
rm -rf "$STATIC_DIR"/*

# Copy new build artifacts (Vite builds to dist/)
echo "📋 Copying new frontend build to Spring Boot..."
cp -r web/dist/* "$STATIC_DIR/"

# 3. Build Backend
echo "☕ Building Backend (Spring Boot)..."
cd backend/todue
# Using -DskipTests to speed up deploy, remove if you want to run tests every time
./mvnw clean package -DskipTests

# Locate the built JAR (ignoring the .original file generated by Maven)
BUILT_JAR=$(ls target/*.jar | grep -v '\.original$' | head -n 1)
echo "✅ Backend built: $BUILT_JAR"

# Go back to root
cd ../..

# 4. Transfer to VPS
echo "📤 Uploading JAR and Service File to VPS ($VPS_HOST)..."
scp "backend/todue/$BUILT_JAR" "$VPS_USER@$VPS_HOST:$VPS_DEST_DIR/$JAR_NAME"
scp "todue.service" "$VPS_USER@$VPS_HOST:$VPS_DEST_DIR/todue.service"
ssh "$VPS_USER@$VPS_HOST" "sudo mv $VPS_DEST_DIR/todue.service /etc/systemd/system/todue.service && sudo mkdir -p /var/log/todue && sudo chown $VPS_USER:$VPS_USER /var/log/todue"

# 5. Restart Service
echo "🔄 Reloading Daemon, Enabling and Restarting Service..."
ssh "$VPS_USER@$VPS_HOST" "sudo systemctl daemon-reload && sudo systemctl enable $SERVICE_NAME && sudo systemctl restart $SERVICE_NAME"

echo "=========================================="
echo "✨ Deployment Complete!"
echo "=========================================="
